Add support for strongly typed entitlements for usePlanshipCustomer hook
planship/planship-react pull request #7
Opened 2024-06-18 21:22 UTC by pwojnaro

This PR, when merged, will add support for a strongly typed entitlements wrapper class when using `usePlanshipCustomer` hook. 

Example:

```
export class ClickerEntitlements extends EntitlementsBase {

  get subscriptionButtonClicks(): number {
    return this.entitlementsDict?.['subscription-button-clicks'].valueOf()
  }
  
  get buttonClicksPerMinute(): number {
    return this.entitlementsDict?.['button-clicks-per-minute'].valueOf()
  }
  
  get maxProjects(): number {
    return this.entitlementsDict?.['max-projects'].valueOf()
  }
  
  get premiumButton(): boolean {
    return this.entitlementsDict?.['premium-button'].valueOf()
  }
  
  get analyticsPanel(): boolean {
    return this.entitlementsDict?.['analytics-panel'].valueOf()
  }
  
  get projectTypes(): [] {
    return this.entitlementsDict?.['project-types'].valueOf()
  }
}

{ entitlements } = usePlanshipCustomer<ClickerEntitlements>(ClickerEntitlements)

// entitlements is of ClickerEntitlements type

```

2024-08-26 23:58 UTC, trentpeterson requested changes

2024-08-26 23:58 UTC, trentpeterson commented on README.md
> +When consuming PlanshipCustomer context in a TypeScript project, entitlements can be defined as a class with getters for individual levers, and passed to the `usePlanshipCustomer` hook.
-> *the* PlanshipCustomer context

Remove comma after levers

2024-08-26 23:58 UTC, trentpeterson commented on README.md
>  By default, all components in a Next.js app are React Server Components. React Server Components don't allow for consuming React context *directly*, so Planship context providers cannot by used *as i
wrap them your own -> wrap them in your own

2024-08-26 23:58 UTC, trentpeterson commented on README.md
> +This pattern can be explored in more detail in our Next.js app example app at https://github.com/planship/planship-nextjs-example
Next.js app example app -> Next.js example app

2024-08-26 23:58 UTC, trentpeterson commented on src/usePlanshipCustomer.ts
> +  if (entitlementsType)
Not sure if we're enforcing braces around if logic...

2024-08-26 23:58 UTC, trentpeterson commented on static/entitlements-vscode.gif
Should consider running this through an app to shrink the size a bit. Nearly 400kb - could likely be sped up, frames removed, etc.

2024-08-27 00:00 UTC, trentpeterson commented on README.md
> +This is helpful in certain IDEs like VS Code where it unlocks a full autocomplete experience for pricing entitlements entitlements.
Copy the language from the Vue module.

2024-08-28 16:53 UTC, pwojnaro commented on src/usePlanshipCustomer.ts
> +  if (entitlementsType)
No, we do not. I just added it to eslint.rc, but I don't believe I enforce it in any other project (not a part of the recommended ruleset, seems arbitrary).

2024-08-28 16:53 UTC, pwojnaro commented on static/entitlements-vscode.gif
I got it down to 220k

2024-08-29 23:23 UTC, trentpeterson requested changes

2024-08-29 23:23 UTC, trentpeterson commented on README.md
> +When working with the entitlements dictionary returned by `usePlanshipCustomer` hook, it can be useful to wrap it in an object with getters for individual levers.
returned by `usePlanshipCustomer` -> returned by the `usePlanshipCustomer`

2024-08-29 23:26 UTC, trentpeterson commented on src/usePlanshipCustomer.ts
> +  if (entitlementsType)
Yeah, just thinking we should be consistent. No strong opinion but if the logic is on a separate line than the subsequent code it seems like braces help make it clearer.

2024-08-30 14:41 UTC, pwojnaro reviewed
Addressed additional feedback

2024-09-03 17:13 UTC, trentpeterson approved these changes
LGTM

2024-09-03 18:48 UTC, merged